name: "Server Deployment"

on:
  push:
    branches: 
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository main branch
      uses: actions/checkout@v2
    - name: curl deployment
      uses: wei/curl@v1
      with:
        args: --user ${{secrets.SSH_USER}}:${{secrets.SSH_PASS}} -T test.html 
sftp://${{secrets.WEBSERVER_ADDRESS}}/www/staging/avm/
