name: "Server Deployment"

on:
  push:
    branches: 
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository main branch
      uses: actions/checkout@v2
    - name: List contents
      run: |
        # multi-line commands are OK apparently
        echo "List the contents of the directory"
        ls
    - name: Say Hello!
      run: echo "Hello there!"
