name: "Server Deployment"

on:
  push:
    branches: 
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository main branch
      uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: ./*.html
        remote_path: www/staging/avm/
        remote_host: ${{secrets.WEBSERVER_ADDRESS}}
        remote_user: ${{secrets.SSH_USER}}
        remote_key_pass: ${{secrets.SSH_PASS}}
